### ISSUE TITLE
Unable to unmarshal to map[string]interface or interface types

### ISSUE THREAD

**Issue by BoskyWSMFN** [nil-go/konf#459]
I encountered difficulties with converting configuration values into [`amqp.Table`](https://github.com/rabbitmq/amqp091-go/blob/dc67c21576c230f589636319f05b7262915313e6/types.go#L392) (`map[string]any`). As far as I understand, converting values into a variable of type `interface{}` is [not supported](https://github.com/nil-go/konf/blob/0d1fce15198d945397510c32a984d3a81a7c10f9/internal/convert/converter.go#L95C59-L95C60), although implementing this would be quite straightforward. My question is: would I break anything globally if I add support for converting the configuration into `interface{}`? Of course, I will add the appropriate unit test.

**Comment by ktong** [comment]
it should be straightforward with one thing in mind: unpack the key if necessary https://github.com/nil-go/konf/blob/main/internal/maps/value.go#L15

**Comment by ktong** [comment]
It should support mapping to map: https://github.com/nil-go/konf/blob/main/internal/convert/converter.go#L84. I will double check later to see if it’s a bug.

**Comment by ktong** [comment]
Found it. It needs to add `case reflect.Interface:` in convert:)
